CREATE TABLE IF NOT EXISTS staging.load_run (
    batch_id VARCHAR NOT NULL,
    api_name VARCHAR NOT NULL,
    transform_version VARCHAR NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status VARCHAR NOT NULL,
    expected_rows BIGINT NOT NULL DEFAULT 0,
    staged_rows BIGINT NOT NULL DEFAULT 0,
    inserted_rows BIGINT NOT NULL DEFAULT 0,
    error_message VARCHAR,
    PRIMARY KEY (batch_id, transform_version)
);

CREATE TABLE IF NOT EXISTS staging.race_result (
    staging_row_id VARCHAR PRIMARY KEY,
    batch_id VARCHAR NOT NULL,
    request_id VARCHAR NOT NULL,
    raw_file_id VARCHAR NOT NULL,
    raw_sha256 VARCHAR NOT NULL,
    source_row_number INTEGER NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL,
    transform_version VARCHAR NOT NULL,
    source_item_json JSON NOT NULL,
    age VARCHAR, ageCond VARCHAR, buG1fAccTime VARCHAR, buG1fOrd VARCHAR,
    buG2fAccTime VARCHAR, buG2fOrd VARCHAR, buG3fAccTime VARCHAR, buG3fOrd VARCHAR,
    buG4fAccTime VARCHAR, buG4fOrd VARCHAR, buG6fAccTime VARCHAR, buG6fOrd VARCHAR,
    buG8fAccTime VARCHAR, buG8fOrd VARCHAR, buS1fAccTime VARCHAR, buS1fOrd VARCHAR,
    buS1fTime VARCHAR, bu_10_8fTime VARCHAR, bu_1fGTime VARCHAR, bu_2fGTime VARCHAR,
    bu_3fGTime VARCHAR, bu_4_2fTime VARCHAR, bu_6_4fTime VARCHAR, bu_8_6fTime VARCHAR,
    budam VARCHAR, buga1 VARCHAR, buga2 VARCHAR, buga3 VARCHAR,
    chaksun1 VARCHAR, chaksun2 VARCHAR, chaksun3 VARCHAR, chaksun4 VARCHAR,
    chaksun5 VARCHAR, chulNo VARCHAR, diffUnit VARCHAR, hrName VARCHAR,
    hrNameEn VARCHAR, hrNo VARCHAR, ilsu VARCHAR, jeG1fTime VARCHAR,
    jeG3fTime VARCHAR, jeS1fTime VARCHAR, je_1cTime VARCHAR, je_2cTime VARCHAR,
    je_3cTime VARCHAR, je_4cTime VARCHAR, jkName VARCHAR, jkNameEn VARCHAR,
    jkNo VARCHAR, meet VARCHAR, name VARCHAR, ord VARCHAR, owName VARCHAR,
    owNameEn VARCHAR, owNo VARCHAR, plcOdds VARCHAR, prizeCond VARCHAR,
    rank VARCHAR, rating VARCHAR, rcDate VARCHAR, rcDay VARCHAR, rcDist VARCHAR,
    rcName VARCHAR, rcNo VARCHAR, rcTime VARCHAR, seG1fAccTime VARCHAR,
    seG3fAccTime VARCHAR, seS1fAccTime VARCHAR, se_1cAccTime VARCHAR,
    se_2cAccTime VARCHAR, se_3cAccTime VARCHAR, se_4cAccTime VARCHAR,
    sex VARCHAR, sexCond VARCHAR, sjG1fOrd VARCHAR, sjG3fOrd VARCHAR,
    sjS1fOrd VARCHAR, sj_1cOrd VARCHAR, sj_2cOrd VARCHAR, sj_3cOrd VARCHAR,
    sj_4cOrd VARCHAR, trName VARCHAR, trNameEn VARCHAR, trNo VARCHAR,
    track VARCHAR, weather VARCHAR, wgBudam VARCHAR, wgHr VARCHAR, winOdds VARCHAR,
    ord_numeric INTEGER,
    ord_parse_valid BOOLEAN NOT NULL,
    UNIQUE (raw_file_id, source_row_number)
);

CREATE TABLE IF NOT EXISTS staging.sales_dividend (
    staging_row_id VARCHAR PRIMARY KEY,
    batch_id VARCHAR NOT NULL,
    request_id VARCHAR NOT NULL,
    raw_file_id VARCHAR NOT NULL,
    raw_sha256 VARCHAR NOT NULL,
    source_row_number INTEGER NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL,
    transform_version VARCHAR NOT NULL,
    source_item_json JSON NOT NULL,
    amt VARCHAR,
    meet VARCHAR,
    odds VARCHAR,
    pool VARCHAR,
    rcDate VARCHAR,
    rcNo VARCHAR,
    amt_numeric DECIMAL(20, 0),
    amt_parse_valid BOOLEAN NOT NULL,
    UNIQUE (raw_file_id, source_row_number)
);
